spring:
  datasource:
    username: admin
    password: pwd
    url: jdbc:postgresql://localhost:5433/registration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
